src/Entity/Reservations.php
<?php

namespace App\Entity;

use App\Repository\ReservationsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationsRepository::class)]
class Reservations
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 50)]
    private $email;

    #[ORM\Column(type: 'integer')]
    private $telephone;

    #[ORM\Column(type: 'integer')]
    private $nombre_de_personnes;

    #[ORM\Column(type: 'time')]
    private $heures;

    #[ORM\Column(type: 'date')]
    private $date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getNombreDePersonnes(): ?int
    {
        return $this->nombre_de_personnes;
    }

    public function setNombreDePersonnes(int $nombre_de_personnes): self
    {
        $this->nombre_de_personnes = $nombre_de_personnes;

        return $this;
    }

    public function getHeures(): ?\DateTimeInterface
    {
        return $this->heures;
    }

    public function setHeures(\DateTimeInterface $heures): self
    {
        $this->heures = $heures;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Form/ReservationsType.php
<?php

namespace App\Form;

use App\Entity\Reservations;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TimeType ;
use Symfony\Component\Form\Extension\Core\Type\DateType ;
use Symfony\Component\Form\Extension\Core\Type\EmailType ;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Validator\Constraints as Assert;


class ReservationsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom' ,TextType::class,[
                
                'attr' => [
                    'class' => 'form-control',
                    'min' => '2',
                    'max' => '100'
                ],
                'label' => 'Nom',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\Length(['min' => 2, 'max' => 100]),
                    new Assert\NotBlank()
                ]
            ])
            
            ->add('email',EmailType::class,[
                'attr' => [
                    'class' => 'form-control',
                    'min' => '2',
                    'max' => '100'
                ],
                'label' => 'Adresse e-mail',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\Length(['min' => 2, 'max' => 100]),
                    new Assert\NotBlank()
                ]  
            ])
            
            ->add('telephone', TelType::class,[
                
            
                'attr' => [
                    'class' => 'form-control',
                    'min' => '10',
                    'max' => '10'
                ],
                'label' => 'Téléphone',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\Length(['min' => 10, 'max' => 10]),
                    new Assert\NotBlank(),
                    new Assert\Positive()
                ]
            
            ])

            
            ->add('nombre_de_personnes',IntegerType::class,[
                
                'attr' => [
                    'class' => 'form-control',
                    'min' => '1',
                    'max' => '100'
                ],
                'label' => 'Nombre de couverts',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\Length(['min' => 1, 'max' => 100]),
                    new Assert\NotBlank(),
                    new Assert\Positive()
                ]
            ])


            
            ->add('heures',TimeType ::class,[
                'hours' => [12,13,14,19, 20, 21, 22,] 
            ] )
            
            ->add('date' , DateType ::class,[
                'years' => [2022,2023] ,
                'placeholder' =>[
                    'year' => 'Year', 'month' => 'Month', 'day' => 'Day',
                    'hour' => 'Hour', 'minute' => 'Minute', 'second' => 'Second',
                ]
             ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservations::class,
        ]);
    }
}

src/Controller/ReservationsController.php
<?php

namespace App\Controller;

use App\Entity\Reservations;
use App\Form\ReservationsType;
use App\Repository\ReservationsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/reservations')]
class ReservationsController extends AbstractController
{
    #[Route('/', name: 'app_reservations_index', methods: ['GET'])]
    public function index(ReservationsRepository $reservationsRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        return $this->render('reservations/index.html.twig', [
            'reservations' => $reservationsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_reservations_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReservationsRepository $reservationsRepository): Response
    {
        $reservation = new Reservations();
        $form = $this->createForm(ReservationsType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationsRepository->add($reservation);
            return $this->redirectToRoute('app_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservations/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservations_show', methods: ['GET'])]
    public function show(Reservations $reservation): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        return $this->render('reservations/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reservations_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservations $reservation, ReservationsRepository $reservationsRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $form = $this->createForm(ReservationsType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationsRepository->add($reservation);
            return $this->redirectToRoute('/', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservations/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservations_delete', methods: ['POST'])]
    public function delete(Request $request, Reservations $reservation, ReservationsRepository $reservationsRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $reservationsRepository->remove($reservation);
        }

        return $this->redirectToRoute('app_reservations_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservations/_delete_form.html.twig
<form method="post" action="{{ path('app_reservations_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservations/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservations/edit.html.twig
{{ include('headerAdmin/headerAdmin.php') }}



{% block body %}
    <h1>Edit Reservations</h1>
<div class ="mx-auto" style ="width:200px; margin-top:0hem;">
    {{ include('reservations/_form.html.twig', {'button_label': 'Update'}) }}
</diV>
    <a href="{{ path('app_reservations_index') }}">back to list</a>

    {{ include('reservations/_delete_form.html.twig') }}
{% endblock %}

templates/reservations/index.html.twig
 {% block stylesheets %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        {% endblock %}
{% block title %}Reservations index/Admin{% endblock %}

{% block body %}
{{ include('headerAdmin/headerAdmin.php') }}
    <h1>Reservations index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Email</th>
                <th>Telephone</th>
                <th>Nombre_de_personnes</th>
                <th>Heures</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.nom }}</td>
                <td>{{ reservation.email }}</td>
                <td>{{ reservation.telephone }}</td>
                <td>{{ reservation.nombreDePersonnes }}</td>
                <td>{{ reservation.heures ? reservation.heures|date('H:i:s') : '' }}</td>
                <td>{{ reservation.date ? reservation.date|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_reservations_show', {'id': reservation.id}) }}">show</a>
                    <a href="{{ path('app_reservations_edit', {'id': reservation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('app_reservations_new') }}">Create new</a> #}
{% endblock %}

templates/reservations/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservations{% endblock %}

{% block body %}
    <h2 class = "H2reservation">RESERVEZ VOTRE TABLE</h2>
<div class ="mx-auto" style ="width:200px; margin-top:5em; margin-left:35em;">
    {{ include('reservations/_form.html.twig') }}
</div>
    {# <a href="{{ path('app_reservations_index') }}">back to list</a> #}
{% endblock %}

templates/reservations/show.html.twig
{{ include('headerAdmin/headerAdmin.php') }}
 {% block stylesheets %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        {% endblock %}
{% block title %}Reservations{% endblock %}

{% block body %}
    <h1>Reservations</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ reservation.nom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ reservation.email }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ reservation.telephone }}</td>
            </tr>
            <tr>
                <th>Nombre_de_personnes</th>
                <td>{{ reservation.nombreDePersonnes }}</td>
            </tr>
            <tr>
                <th>Heures</th>
                <td>{{ reservation.heures ? reservation.heures|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ reservation.date ? reservation.date|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reservations_index') }}">back to list</a>

    <a href="{{ path('app_reservations_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservations/_delete_form.html.twig') }}
{% endblock %}